server:
    port: 20090

api:
    endpoint: http://openapi.data.go.kr/openapi/service/rest/Covid19/
    name: getCovid19InfStateJson

slack:
    value:
        hooks: ${slack.value.hooks}
        username: ByeVirus2

logging:
    file:
        name: /log/202011/ByeVirus2.log
